name: MineTeller
main: com.modcrafting.mineteller.MineTeller
version: 0.1
description: A plugin that gets notified when votes are made from MinecraftCasino.
authors: [Built From Votifier -Deathmarine]